### PR TITLE
Supports multiple bing cookie for Docker and fly.io.

### PR DESCRIPTION
**Pull request by F4ria**
Supports multiple bing cookie for Docker and fly.io.

### CODE REVIEW

**Comment by yihong0618** [comment]
do not do the break change…

**Comment by yihong0618** [comment]
sorry for that, IMO for now most some of our users do not know much about code, and break change may confuse, this is my fault the design problem sorry for that, so we can not merge if we have some break change.
@BeautyyuYanli what do you think?

**Comment by BeautyyuYanli** [comment]
1. Is it necessary to run the code without args?
2. If yes, we may create a wrapper entry point for fly.io, to avoid breaking change of tg.py

**Comment by BeautyyuYanli** [comment]
You may notice #16  that may be helpful

**Pull request closed without merging**
